
ccflags-y += -I$(srctree)/drivers/spi/mediatek/mt6580
ccflags-y += -I$(srctree)/arch/arm64/include/asm
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include
subdir-ccflags-y += -Werror
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/mt6580/
obj-y += slspi_androidM_original.o sl_proc.o 
