#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include \
					-I$(srctree)/drivers/misc/mediatek/include/mt-plat


obj-y += sunwavecorp.o
obj-y += platform.o
obj-y += misce.o
obj-y += mt6735.o
obj-y += mt6735_plat.o
obj-y += sw_fingerprint.o
